## Sass linter config ##

rules:
  at-rule-no-unknown: true
  block-no-empty: true
  color-no-invalid-hex: true
  comment-no-empty: true
  declaration-block-no-duplicate-properties: true
  indentation: 2
  length-zero-no-unit: true
  max-nesting-depth: 5
  no-empty-source: true
  no-extra-semicolons: true
  no-eol-whitespace: true
  selector-type-no-unknown: true
  unit-no-unknown: true
